const mongoose = require('mongoose');
require('dotenv').config();
const Question = require('./models/Question');

const all120Questions = [
    // ==========================================
    // REACT BASICS & ADVANCED (30 Questions)
    // ==========================================
    { topic: 'React Basics & Advanced', question: 'What is the purpose of the Virtual DOM in React?', options: ['To directly manipulate the browser DOM', 'To improve performance by minimizing direct DOM updates', 'To create virtual reality interfaces', 'To store data securely'], correctAnswer: 'To improve performance by minimizing direct DOM updates', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'Which Hook is used to perform side effects in a functional component?', options: ['useState', 'useContext', 'useEffect', 'useReducer'], correctAnswer: 'useEffect', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What is "Prop Drilling" in React?', options: ['Passing props through multiple nested components to reach a child', 'Drilling holes in the motherboard', 'A tool to fetch data from APIs', 'A new React compiler feature'], correctAnswer: 'Passing props through multiple nested components to reach a child', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'Which tool is built into React to solve Prop Drilling?', options: ['Redux', 'MobX', 'Context API', 'React Router'], correctAnswer: 'Context API', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What does the `useState` hook return?', options: ['An object with state and props', 'An array containing the current state and a function to update it', 'A boolean indicating if the component rendered', 'Nothing'], correctAnswer: 'An array containing the current state and a function to update it', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What is JSX?', options: ['A syntax extension for JavaScript', 'A new programming language', 'A database format', 'A styling framework'], correctAnswer: 'A syntax extension for JavaScript', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'Which method is used to render a list of items in React?', options: ['.filter()', '.reduce()', '.map()', '.forEach()'], correctAnswer: '.map()', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What is a React Fragment?', options: ['A broken piece of UI', 'A way to group multiple elements without adding an extra node to the DOM', 'A deprecated feature', 'A specialized React router component'], correctAnswer: 'A way to group multiple elements without adding an extra node to the DOM', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'How do you pass data from a parent component to a child component?', options: ['Using State', 'Using Props', 'Using Redux', 'Using LocalStorage'], correctAnswer: 'Using Props', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What is the correct syntax for a React functional component?', options: ['function MyComponent() { return <div>Hello</div>; }', 'class MyComponent extends React.Component {}', 'const MyComponent = {}', 'new Component()'], correctAnswer: 'function MyComponent() { return <div>Hello</div>; }', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What does `useMemo` do?', options: ['Memorizes user passwords', 'Caches a calculation result between renders', 'Fetches data from an API', 'Re-renders the component infinitely'], correctAnswer: 'Caches a calculation result between renders', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'What is the main difference between `useMemo` and `useCallback`?', options: ['useMemo caches a value, useCallback caches a function', 'useMemo is for classes, useCallback is for functions', 'There is no difference', 'useCallback is faster'], correctAnswer: 'useMemo caches a value, useCallback caches a function', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'Which hook allows you to access DOM elements directly?', options: ['useDOM', 'useEffect', 'useRef', 'useState'], correctAnswer: 'useRef', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is a Higher-Order Component (HOC)?', options: ['A component that renders at the top of the screen', 'A function that takes a component and returns a new component', 'A component with a z-index of 999', 'A built-in React routing method'], correctAnswer: 'A function that takes a component and returns a new component', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'Why do we need "keys" in React lists?', options: ['To encrypt data', 'To help React identify which items have changed, been added, or removed', 'To unlock pro features', 'To connect to the database'], correctAnswer: 'To help React identify which items have changed, been added, or removed', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is a "Controlled Component" in React?', options: ['A component controlled by Redux', 'An input element whose value is controlled by React state', 'A component with strict CSS rules', 'A component that cannot be deleted'], correctAnswer: 'An input element whose value is controlled by React state', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What does `React.StrictMode` do?', options: ['Forces you to use TypeScript', 'Highlights potential problems in an application during development', 'Prevents the app from crashing in production', 'Makes the app run 2x faster'], correctAnswer: 'Highlights potential problems in an application during development', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'How can you catch JavaScript errors anywhere in your child component tree?', options: ['Using try/catch blocks everywhere', 'Using Error Boundaries', 'Using Redux Middlewares', 'Using useError hook'], correctAnswer: 'Using Error Boundaries', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'What is the purpose of React Portals?', options: ['To teleport components to another server', 'To render children into a DOM node that exists outside the DOM hierarchy of the parent component', 'To create 3D animations', 'To manage API endpoints'], correctAnswer: 'To render children into a DOM node that exists outside the DOM hierarchy of the parent component', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'Which method is used to dynamically load components to improve performance?', options: ['React.lazy()', 'React.fast()', 'React.dynamic()', 'React.load()'], correctAnswer: 'React.lazy()', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is a Custom Hook?', options: ['A hook downloaded from NPM only', 'A JavaScript function whose name starts with "use" and calls other hooks', 'A hook used for hacking', 'A premium React feature'], correctAnswer: 'A JavaScript function whose name starts with "use" and calls other hooks', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'In class components, which lifecycle method runs after the component is rendered for the first time?', options: ['componentWillMount', 'componentDidMount', 'componentDidUpdate', 'render'], correctAnswer: 'componentDidMount', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is Babel primarily used for in a React project?', options: ['Styling CSS', 'Converting JSX and ES6 code into backward-compatible JavaScript', 'Database management', 'Hosting the application'], correctAnswer: 'Converting JSX and ES6 code into backward-compatible JavaScript', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is Webpack?', options: ['A module bundler that bundles JavaScript files for usage in a browser', 'A React UI library', 'A state management tool', 'A backend framework'], correctAnswer: 'A module bundler that bundles JavaScript files for usage in a browser', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is the difference between React and React Native?', options: ['React is for web, React Native is for mobile apps', 'React Native is older', 'React is for backend, Native is for frontend', 'There is no difference'], correctAnswer: 'React is for web, React Native is for mobile apps', difficulty: 'easy' },
    { topic: 'React Basics & Advanced', question: 'What is Redux?', options: ['A color palette', 'A predictable state container for JavaScript apps', 'A database', 'A router'], correctAnswer: 'A predictable state container for JavaScript apps', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'In Redux, what is an "Action"?', options: ['A function that mutates state', 'A plain JavaScript object describing what happened', 'A network request', 'A CSS animation'], correctAnswer: 'A plain JavaScript object describing what happened', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'In Redux, what does a "Reducer" do?', options: ['Reduces the app size', 'Takes current state and an action, and returns a new state', 'Deletes old data', 'Fetches APIs'], correctAnswer: 'Takes current state and an action, and returns a new state', difficulty: 'hard' },
    { topic: 'React Basics & Advanced', question: 'Is `setState` in React sync or async?', options: ['Synchronous', 'Asynchronous', 'Depends on the browser', 'It is neither'], correctAnswer: 'Asynchronous', difficulty: 'medium' },
    { topic: 'React Basics & Advanced', question: 'What is a Synthetic Event in React?', options: ['A fake event that crashes the app', 'A cross-browser wrapper around the browsers native event', 'An AI generated event', 'An event that triggers automatically'], correctAnswer: 'A cross-browser wrapper around the browsers native event', difficulty: 'hard' },

    // ==========================================
    // NODE.JS (30 Questions)
    // ==========================================
    { topic: 'Node.js', question: 'Node.js is primarily used for building what kind of applications?', options: ['Mobile Apps', 'Browser extensions', 'Server-side and networking applications', 'Operating systems'], correctAnswer: 'Server-side and networking applications', difficulty: 'easy' },
    { topic: 'Node.js', question: 'Which engine powers Node.js under the hood?', options: ['SpiderMonkey', 'Google V8 JavaScript Engine', 'Chakra', 'JavaScriptCore'], correctAnswer: 'Google V8 JavaScript Engine', difficulty: 'easy' },
    { topic: 'Node.js', question: 'What is the purpose of the `package.json` file?', options: ['To hold metadata and dependencies for the project', 'To write the main server code', 'To store the database credentials', 'To compile the JavaScript code'], correctAnswer: 'To hold metadata and dependencies for the project', difficulty: 'easy' },
    { topic: 'Node.js', question: 'Which built-in module is used to handle file operations in Node.js?', options: ['http', 'fs', 'url', 'path'], correctAnswer: 'fs', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What does "Event-Driven" mean in Node.js?', options: ['The server runs only on specific calendar events', 'Execution is driven by events like clicks or network requests', 'It generates event tickets', 'It requires event loops from other languages'], correctAnswer: 'Execution is driven by events like clicks or network requests', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What is Express.js?', options: ['A database for Node.js', 'A fast, unopinionated web framework for Node.js', 'A frontend library', 'A testing tool'], correctAnswer: 'A fast, unopinionated web framework for Node.js', difficulty: 'easy' },
    { topic: 'Node.js', question: 'How do you export a module in Node.js (CommonJS)?', options: ['export default', 'module.exports', 'exports.module', 'import'], correctAnswer: 'module.exports', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What is "Callback Hell"?', options: ['A server crash', 'Heavily nested callbacks that make code hard to read', 'A security vulnerability', 'A Node.js specific error code'], correctAnswer: 'Heavily nested callbacks that make code hard to read', difficulty: 'medium' },
    { topic: 'Node.js', question: 'Is Node.js single-threaded or multi-threaded?', options: ['Multi-threaded', 'Single-threaded but highly scalable via event loop', 'Dual-threaded', 'Depends on the CPU'], correctAnswer: 'Single-threaded but highly scalable via event loop', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What is NPM?', options: ['Node Package Manager', 'Node Project Maker', 'New Program Module', 'Network Protocol Manager'], correctAnswer: 'Node Package Manager', difficulty: 'easy' },
    { topic: 'Node.js', question: 'What is the purpose of `package-lock.json`?', options: ['To lock the source code', 'To lock the exact versions of installed dependencies', 'To create user passwords', 'To prevent DDOS attacks'], correctAnswer: 'To lock the exact versions of installed dependencies', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What is a "Stream" in Node.js?', options: ['A video playing module', 'Objects that let you read data or write data continuously', 'A CSS styling framework', 'A database connection string'], correctAnswer: 'Objects that let you read data or write data continuously', difficulty: 'hard' },
    { topic: 'Node.js', question: 'What is a "Buffer" in Node.js?', options: ['A temporary storage area for raw binary data', 'A waiting screen for users', 'A security wall', 'A tool to clear cache'], correctAnswer: 'A temporary storage area for raw binary data', difficulty: 'hard' },
    { topic: 'Node.js', question: 'Which class is used to create and listen to custom events in Node.js?', options: ['EventCreator', 'EventEmitter', 'EventBuilder', 'EventHook'], correctAnswer: 'EventEmitter', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What does the `process` object do in Node.js?', options: ['Stops the computer', 'Provides info and control over the current Node.js process', 'Processes payments', 'Runs Python code'], correctAnswer: 'Provides info and control over the current Node.js process', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What does `__dirname` return?', options: ['The name of the user directory', 'The absolute path of the directory containing the currently executing file', 'The IP address of the server', 'The database URL'], correctAnswer: 'The absolute path of the directory containing the currently executing file', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What is Middleware in Express.js?', options: ['Hardware components', 'Functions that have access to the request, response, and the next function', 'A type of database', 'A styling tool'], correctAnswer: 'Functions that have access to the request, response, and the next function', difficulty: 'hard' },
    { topic: 'Node.js', question: 'Which command installs an NPM package globally?', options: ['npm install <pkg>', 'npm install -g <pkg>', 'npm global <pkg>', 'npm add <pkg>'], correctAnswer: 'npm install -g <pkg>', difficulty: 'easy' },
    { topic: 'Node.js', question: 'What is the modern alternative to callbacks for handling asynchronous operations?', options: ['Promises and Async/Await', 'Synchronous blocks', 'Event Loops', 'Buffers'], correctAnswer: 'Promises and Async/Await', difficulty: 'easy' },
    { topic: 'Node.js', question: 'What does REPL stand for?', options: ['Read Eval Print Loop', 'Run Every Process Locally', 'Read Execute Print Log', 'Random Event Process Loop'], correctAnswer: 'Read Eval Print Loop', difficulty: 'medium' },
    { topic: 'Node.js', question: 'Which module provides utilities for working with file and directory paths?', options: ['dir', 'path', 'filesystem', 'navigate'], correctAnswer: 'path', difficulty: 'easy' },
    { topic: 'Node.js', question: 'Which module provides basic cryptographic functions?', options: ['crypto', 'hash', 'security', 'encrypt'], correctAnswer: 'crypto', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What does CORS stand for?', options: ['Cross-Origin Resource Sharing', 'Computer Oriented Response System', 'Centralized Object Rendering Server', 'Code Optimization Range System'], correctAnswer: 'Cross-Origin Resource Sharing', difficulty: 'hard' },
    { topic: 'Node.js', question: 'What is JWT?', options: ['Java Web Toolkit', 'JSON Web Token used for secure authentication', 'JavaScript Window Timer', 'JSON Wide Transfer'], correctAnswer: 'JSON Web Token used for secure authentication', difficulty: 'medium' },
    { topic: 'Node.js', question: 'What does REST stand for in API design?', options: ['Responsive Execution Standard Tools', 'Representational State Transfer', 'Random Event Server Technology', 'Routing Express Server Types'], correctAnswer: 'Representational State Transfer', difficulty: 'medium' },
    { topic: 'Node.js', question: 'How can you scale a Node.js application to use multiple CPU cores?', options: ['By using the `cluster` module', 'By installing more RAM', 'By writing shorter code', 'Node.js cannot use multiple cores'], correctAnswer: 'By using the `cluster` module', difficulty: 'hard' },
    { topic: 'Node.js', question: 'Which module is used to spawn new processes in Node.js?', options: ['new_process', 'spawn', 'child_process', 'fork_process'], correctAnswer: 'child_process', difficulty: 'hard' },
    { topic: 'Node.js', question: 'What is the default port for HTTP traffic?', options: ['80', '443', '8080', '3000'], correctAnswer: '80', difficulty: 'easy' },
    { topic: 'Node.js', question: 'What is the difference between `setImmediate()` and `setTimeout()`?', options: ['No difference', 'setImmediate executes after current poll phase, setTimeout after a given delay', 'setTimeout is for frontend only', 'setImmediate is deprecated'], correctAnswer: 'setImmediate executes after current poll phase, setTimeout after a given delay', difficulty: 'hard' },
    { topic: 'Node.js', question: 'What status code implies a "Not Found" error?', options: ['200', '500', '404', '403'], correctAnswer: '404', difficulty: 'easy' },

    // ==========================================
    // MONGODB (30 Questions)
    // ==========================================
    { topic: 'MongoDB', question: 'What type of database is MongoDB?', options: ['Relational Database (SQL)', 'Graph Database', 'NoSQL Document Database', 'Key-Value Store'], correctAnswer: 'NoSQL Document Database', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'In MongoDB, data is stored in a format similar to JSON called...', options: ['XML', 'BSON', 'CSV', 'YAML'], correctAnswer: 'BSON', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is the equivalent of a relational "Table" in MongoDB?', options: ['Document', 'Collection', 'Database', 'Field'], correctAnswer: 'Collection', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is the equivalent of a relational "Row" in MongoDB?', options: ['Column', 'Collection', 'Document', 'Index'], correctAnswer: 'Document', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'Every document in MongoDB automatically gets which unique field?', options: ['_id', 'primary_key', 'uuid', 'id'], correctAnswer: '_id', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is Mongoose?', options: ['A UI component library', 'An Object Data Modeling (ODM) library for MongoDB and Node.js', 'A frontend framework', 'A cloud hosting provider'], correctAnswer: 'An Object Data Modeling (ODM) library for MongoDB and Node.js', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'What is the default port number for MongoDB?', options: ['3000', '8080', '27017', '3306'], correctAnswer: '27017', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'Which Aggregation pipeline stage is used to filter documents?', options: ['$group', '$project', '$match', '$sort'], correctAnswer: '$match', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'Which Aggregation stage is used to select or exclude specific fields?', options: ['$project', '$filter', '$select', '$group'], correctAnswer: '$project', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'What is the purpose of Indexes in MongoDB?', options: ['To encrypt passwords', 'To improve the speed of search queries', 'To link collections together', 'To delete old data'], correctAnswer: 'To improve the speed of search queries', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'Which method returns only one document that satisfies the criteria?', options: ['find()', 'searchOne()', 'findOne()', 'getOne()'], correctAnswer: 'findOne()', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is a Replica Set in MongoDB?', options: ['A group of MongoDB instances that maintain the same data set', 'A backup file', 'A copy of a single document', 'A testing environment'], correctAnswer: 'A group of MongoDB instances that maintain the same data set', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'What is Sharding in MongoDB?', options: ['Deleting broken data', 'Distributing data across multiple machines (horizontal scaling)', 'Encrypting the database', 'Joining two collections'], correctAnswer: 'Distributing data across multiple machines (horizontal scaling)', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'Which operator is used to update the value of a field?', options: ['$update', '$change', '$set', '$modify'], correctAnswer: '$set', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'Which operator is used to increment a numerical value by a specified amount?', options: ['$add', '$plus', '$inc', '$sum'], correctAnswer: '$inc', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'How do you perform a "Join" in MongoDB aggregation?', options: ['$join', '$lookup', '$merge', '$populate'], correctAnswer: '$lookup', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'In Mongoose, which method is used to replace references with actual document data?', options: ['.join()', '.include()', '.populate()', '.fetch()'], correctAnswer: '.populate()', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'What is GridFS used for?', options: ['Creating grids in UI', 'Storing and retrieving files that exceed the 16 MB BSON-document size limit', 'A new type of index', 'Database sharding'], correctAnswer: 'Storing and retrieving files that exceed the 16 MB BSON-document size limit', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'What is the maximum size of a single BSON document in MongoDB?', options: ['1 MB', '16 MB', '100 MB', 'Unlimited'], correctAnswer: '16 MB', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'What does an "Upsert" do?', options: ['Updates a document if it exists, otherwise inserts a new document', 'Sorts data upwards', 'Deletes the database', 'Replaces the entire collection'], correctAnswer: 'Updates a document if it exists, otherwise inserts a new document', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'What is MongoDB Atlas?', options: ['A book about databases', 'MongoDBs fully managed cloud database service', 'A GUI tool for MongoDB', 'A programming language'], correctAnswer: 'MongoDBs fully managed cloud database service', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is a Cursor in MongoDB?', options: ['The mouse pointer', 'A pointer to the result set of a query', 'A deleted document', 'A type of index'], correctAnswer: 'A pointer to the result set of a query', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'How many bytes make up a MongoDB ObjectId?', options: ['8 bytes', '12 bytes', '16 bytes', '32 bytes'], correctAnswer: '12 bytes', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'Does MongoDB support multi-document ACID transactions?', options: ['No, never', 'Yes, introduced in version 4.0', 'Only in the enterprise edition', 'Yes, since version 1.0'], correctAnswer: 'Yes, introduced in version 4.0', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'How do you drop an entire collection in the mongo shell?', options: ['db.collection.drop()', 'db.drop(collection)', 'collection.delete()', 'drop.table(collection)'], correctAnswer: 'db.collection.drop()', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'Which method restricts the number of documents returned in a query?', options: ['stop()', 'limit()', 'max()', 'end()'], correctAnswer: 'limit()', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'Which method is used alongside limit() to create pagination?', options: ['next()', 'page()', 'skip()', 'offset()'], correctAnswer: 'skip()', difficulty: 'medium' },
    { topic: 'MongoDB', question: 'What does the $unwind aggregation stage do?', options: ['Decompresses data', 'Deconstructs an array field from the input documents to output a document for each element', 'Reverses a string', 'Drops an index'], correctAnswer: 'Deconstructs an array field from the input documents to output a document for each element', difficulty: 'hard' },
    { topic: 'MongoDB', question: 'What command shows all databases in the mongo shell?', options: ['list dbs', 'show databases', 'display dbs', 'get databases'], correctAnswer: 'show databases', difficulty: 'easy' },
    { topic: 'MongoDB', question: 'What is the purpose of Database Profiling?', options: ['To create user profiles', 'To collect detailed information about Database Commands executed', 'To style the database UI', 'To generate fake data'], correctAnswer: 'To collect detailed information about Database Commands executed', difficulty: 'hard' },

    // ==========================================
    // DATA STRUCTURES (30 Questions)
    // ==========================================
    { topic: 'Data Structures', question: 'Which data structure follows the LIFO (Last In, First Out) principle?', options: ['Queue', 'Linked List', 'Stack', 'Tree'], correctAnswer: 'Stack', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'Which data structure follows the FIFO (First In, First Out) principle?', options: ['Stack', 'Queue', 'Graph', 'Hash Table'], correctAnswer: 'Queue', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'What is the time complexity of searching in a balanced Binary Search Tree (BST)?', options: ['O(1)', 'O(n)', 'O(n^2)', 'O(log n)'], correctAnswer: 'O(log n)', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is the time complexity of accessing an element in an Array by its index?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n^2)'], correctAnswer: 'O(1)', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'In a Tree data structure, a node with no children is called a...', options: ['Root', 'Branch', 'Leaf', 'Stem'], correctAnswer: 'Leaf', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'What are the two main components of a Graph?', options: ['Nodes and Arrays', 'Vertices and Edges', 'Roots and Leaves', 'Stacks and Queues'], correctAnswer: 'Vertices and Edges', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'What is the primary advantage of a Hash Table?', options: ['Elements are automatically sorted', 'Extremely fast lookups, insertions, and deletions (O(1) average case)', 'It uses zero memory', 'It is easy to visualize'], correctAnswer: 'Extremely fast lookups, insertions, and deletions (O(1) average case)', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What happens when two keys hash to the same index in a Hash Table?', options: ['The table crashes', 'The old value is permanently deleted', 'A Collision occurs', 'The table doubles in size immediately'], correctAnswer: 'A Collision occurs', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'Which data structure is typically used to implement an "Undo" feature in an application?', options: ['Queue', 'Hash Table', 'Stack', 'Graph'], correctAnswer: 'Stack', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'Which data structure is typically used for a Printer Spooler (handling print jobs)?', options: ['Stack', 'Queue', 'Tree', 'Array'], correctAnswer: 'Queue', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'Depth First Search (DFS) on a graph uses which underlying data structure?', options: ['Queue', 'Stack', 'Hash Map', 'Linked List'], correctAnswer: 'Stack', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'Breadth First Search (BFS) on a graph uses which underlying data structure?', options: ['Stack', 'Queue', 'Tree', 'Array'], correctAnswer: 'Queue', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'In a Binary Tree, which traversal visits nodes in the order: Left, Root, Right?', options: ['Preorder', 'Postorder', 'Inorder', 'Level-order'], correctAnswer: 'Inorder', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'In a Binary Tree, which traversal visits nodes in the order: Root, Left, Right?', options: ['Inorder', 'Postorder', 'Preorder', 'Outorder'], correctAnswer: 'Preorder', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is the defining property of a Binary Search Tree (BST)?', options: ['Left child < Parent < Right child', 'All nodes have exactly 2 children', 'It must be perfectly balanced', 'Right child < Parent < Left child'], correctAnswer: 'Left child < Parent < Right child', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'Which sorting algorithm uses a "Divide and Conquer" strategy by selecting a pivot?', options: ['Bubble Sort', 'Insertion Sort', 'Quick Sort', 'Selection Sort'], correctAnswer: 'Quick Sort', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is the worst-case time complexity of Bubble Sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], correctAnswer: 'O(n^2)', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'What is the time complexity of Merge Sort?', options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(1)'], correctAnswer: 'O(n log n)', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'Which data structure is specifically designed for fast string prefix lookups (e.g., Autocomplete)?', options: ['Stack', 'Hash Table', 'Trie (Prefix Tree)', 'Graph'], correctAnswer: 'Trie (Prefix Tree)', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'What is an AVL Tree?', options: ['A tree used for audio processing', 'A Self-balancing Binary Search Tree', 'A tree with infinite children', 'A graph without edges'], correctAnswer: 'A Self-balancing Binary Search Tree', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'When a function calls itself recursively, where is that call stored in memory?', options: ['The Heap', 'The Call Stack', 'The Queue', 'The Hard Drive'], correctAnswer: 'The Call Stack', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is the main advantage of a Linked List over an Array?', options: ['Faster random access', 'Dynamic size and easy insertions/deletions', 'Uses less memory', 'Automatically sorted'], correctAnswer: 'Dynamic size and easy insertions/deletions', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What makes a Doubly Linked List different from a Singly Linked List?', options: ['It holds two values per node', 'Nodes have pointers to both the Next and Previous nodes', 'It is twice as fast', 'It cannot be deleted'], correctAnswer: 'Nodes have pointers to both the Next and Previous nodes', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is a Circular Queue?', options: ['A queue shaped like a circle in memory', 'A queue where the last position connects back to the first position', 'A queue that loops infinitely', 'A queue for round-robin routing only'], correctAnswer: 'A queue where the last position connects back to the first position', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'A Priority Queue is most efficiently implemented using which data structure?', options: ['Array', 'Linked List', 'Heap', 'Stack'], correctAnswer: 'Heap', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'What does Big O notation mathematically describe?', options: ['The exact number of seconds code takes to run', 'The upper bound of the time or space complexity of an algorithm', 'The amount of RAM used', 'The number of lines of code'], correctAnswer: 'The upper bound of the time or space complexity of an algorithm', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'To prevent an infinite loop, every Recursive function must have a...', options: ['For loop', 'Base case', 'Global variable', 'Try/Catch block'], correctAnswer: 'Base case', difficulty: 'easy' },
    { topic: 'Data Structures', question: 'What is Memoization in Dynamic Programming?', options: ['Writing notes in the code', 'Caching the results of expensive function calls to avoid repeating them', 'Storing data in MongoDB', 'Deleting unused memory'], correctAnswer: 'Caching the results of expensive function calls to avoid repeating them', difficulty: 'hard' },
    { topic: 'Data Structures', question: 'Which of these is a way to represent a Graph in memory?', options: ['Adjacency Matrix', 'Binary Search', 'Hash Collision', 'Pivot Table'], correctAnswer: 'Adjacency Matrix', difficulty: 'medium' },
    { topic: 'Data Structures', question: 'What is a Sentinel Node in a Linked List?', options: ['A node that guards the database', 'A dummy node used to simplify edge conditions (like empty lists)', 'The biggest node', 'A deleted node'], correctAnswer: 'A dummy node used to simplify edge conditions (like empty lists)', difficulty: 'hard' }
];

mongoose.connect(process.env.MONGO_URI)
    .then(async () => {
        console.log('Connected to MongoDB! Preparing your massive 120-question database...');
        
        // 1. DELETES all old questions to avoid duplicates/mess
        await Question.deleteMany(); 
        console.log('Old questions wiped clean 🧹');
        
        // 2. INSERTS all 120 new questions at once
        await Question.insertMany(all120Questions);
        console.log('🎉 BOOM! All 120 questions successfully loaded into your database!');
        
        process.exit(); 
    })
    .catch(err => {
        console.error('Error:', err);
        process.exit(1);
    });